import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Product Documentation',
      items: [
        {
          type: 'category',
          label: 'Start Here',
          items: [
            'product/start-here/product-overview',
            'product/start-here/roles-and-access',
            'product/start-here/current-platform-status',
            'product/start-here/glossary',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Documentation',
      items: [
        'architecture-overview',
        'routing-map',
        'state-slices',
        'user-flows',
        'ux-conventions',
        {
          type: 'category',
          label: 'API',
          items: [
            'api/index',
            'api/http-client',
            'api/auth',
            'api/user',
            'api/products',
            'api/calendar',
          ],
        },
        {
          type: 'category',
          label: 'Component Catalog',
          items: [{type: 'autogenerated', dirName: 'components'}],
        },
        {
          type: 'category',
          label: 'Architecture',
          items: [{type: 'autogenerated', dirName: 'architecture'}],
        },
        {
          type: 'category',
          label: 'Playbooks',
          items: [{type: 'autogenerated', dirName: 'playbooks'}],
        },
      ],
    },
  ],
};

export default sidebars;
