import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Product Documentation',
      items: [
        {
          type: 'category',
          label: 'Start Here',
          items: [
            'product/start-here/product-overview',
            'product/start-here/roles-and-access',
            'product/start-here/current-platform-status',
            'product/start-here/glossary',
          ],
        },
        {
          type: 'category',
          label: 'For Customers',
          items: [
            'product/customers/customer-overview',
            'product/customers/exploring-products',
            'product/customers/product-detail-pages',
            'product/customers/wishlist',
            'product/customers/shopping-cart',
            'product/customers/library',
            'product/customers/customer-account-settings',
          ],
        },
        {
          type: 'category',
          label: 'For Administrators',
          items: [
            'product/administrators/admin-overview',
            'product/administrators/managing-users',
            'product/administrators/managing-products',
            'product/administrators/creating-products-for-creators',
            'product/administrators/audit-logs',
          ],
        },
        {
          type: 'category',
          label: 'For Creators',
          items: [
            'product/creators/creator-overview',
            'product/creators/managing-products',
            'product/creators/creating-a-product',
            'product/creators/course-products',
            'product/creators/download-products',
            'product/creators/consultation-products',
            'product/creators/membership-products',
            'product/creators/creator-settings',
            'product/creators/marketing-and-reviews',
            'product/creators/sales-and-analytics-status',
          ],
        },
        {
          type: 'category',
          label: 'Core Concepts',
          items: [
            'product/core-concepts/calendar-connections',
            'product/core-concepts/product-types',
            'product/core-concepts/product-statuses',
            'product/core-concepts/authentication-and-onboarding',
            'product/core-concepts/search-and-discovery',
            'product/core-concepts/local-vs-server-backed-features',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Documentation',
      items: [
        'developer/developer-overview',
        'developer/local-setup',
        'developer/routing-and-access-reference',
        'developer/frontend-api-reference',
        'developer/state-reference',
        'developer/ux-conventions',
        {
          type: 'category',
          label: 'Frontend API Reference',
          items: [
            'developer/api/index',
            'developer/api/http-client',
            'developer/api/auth',
            'developer/api/user',
            'developer/api/products',
            'developer/api/calendar',
          ],
        },
        {
          type: 'category',
          label: 'Component Catalog',
          items: [{type: 'autogenerated', dirName: 'developer/components'}],
        },
        {
          type: 'category',
          label: 'Architecture',
          items: [{type: 'autogenerated', dirName: 'developer/architecture'}],
        },
        {
          type: 'category',
          label: 'Playbooks',
          items: [{type: 'autogenerated', dirName: 'developer/playbooks'}],
        },
      ],
    },
  ],
};

export default sidebars;
